name: Build, Push and Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Release new version
        id: release
        run: |
          bash ./scripts/git_update.sh -v patch 

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          
        run: |
          docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Helm Deploy to EKS
        env:
          IMAGE_TAG: ${{ steps.release.outputs.new-tag }}
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          helm upgrade --install django-release ./django-chart \
            --create-namespace \
            --namespace django-prod \
            -f ./django-chart/values.yaml \
            --set django.image=$ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG \
            --set image.tag=$IMAGE_TAG \
            --set secrets.SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
            --set secrets.POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --set secrets.DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} \
            --set secrets.CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }} \
            --atomic \
            --timeout 120s

      - name: Verify Helm Release
        run: |
          helm status django-release --namespace django-prod